# Generated by Django 3.0.3 on 2020-03-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentus',
            name='tel',
            field=models.IntegerField(default=''),
        ),
    ]
