# Generated by Django 3.0.1 on 2020-05-18 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200518_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
