# Generated by Django 3.0.1 on 2020-05-18 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200518_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shopcart',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
        migrations.DeleteModel(
            name='ShopCart',
        ),
    ]
