# Generated by Django 3.0.1 on 2020-06-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_orderproduct_shopcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Accepted', 'Accepted'), ('prepare', 'prepare'), ('onShopping', 'onShopping'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='New', max_length=20),
        ),
    ]
