# Generated by Django 3.0.1 on 2020-05-10 22:06

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('status', models.CharField(choices=[('True', 'Evet'), ('False', 'Hayir')], default='', max_length=40)),
                ('title', models.CharField(max_length=15)),
                ('about', ckeditor_uploader.fields.RichTextUploadingField()),
                ('keyword', models.TextField(max_length=10000)),
                ('description', models.TextField(max_length=10000)),
                ('company', models.TextField(max_length=10000)),
                ('smtpserver', models.CharField(max_length=44)),
                ('smtpemail', models.CharField(max_length=44)),
                ('smtpPassword', models.CharField(max_length=15)),
                ('smtpPort', models.CharField(max_length=15)),
                ('pagefa', models.CharField(max_length=15)),
                ('pagetw', models.CharField(max_length=15)),
                ('pageyt', models.CharField(max_length=15)),
                ('pageLink', models.CharField(max_length=15)),
                ('pageTe', models.CharField(default=0, max_length=20)),
                ('icon', models.ImageField(blank=True, upload_to='images/')),
                ('name_set', models.CharField(default='-', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=202)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='images/profile_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
