# Generated by Django 3.0.3 on 2020-02-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('about', models.TextField(max_length=10000)),
                ('picurl', models.TextField(default='', max_length=22)),
                ('picname', models.TextField(default='', max_length=22)),
                ('pagefa', models.CharField(max_length=15)),
                ('pagetw', models.CharField(max_length=15)),
                ('pageyt', models.CharField(max_length=15)),
                ('pageLink', models.CharField(max_length=15)),
                ('pageTe', models.CharField(default=0, max_length=20)),
                ('name_set', models.CharField(default='-', max_length=20)),
            ],
        ),
    ]
