# Generated by Django 3.0.1 on 2020-05-10 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='main',
            name='name_set',
        ),
        migrations.RemoveField(
            model_name='main',
            name='pageLink',
        ),
        migrations.RemoveField(
            model_name='main',
            name='pageTe',
        ),
        migrations.RemoveField(
            model_name='main',
            name='pagefa',
        ),
        migrations.RemoveField(
            model_name='main',
            name='pagetw',
        ),
        migrations.RemoveField(
            model_name='main',
            name='pageyt',
        ),
        migrations.RemoveField(
            model_name='main',
            name='smtpPassword',
        ),
        migrations.RemoveField(
            model_name='main',
            name='smtpPort',
        ),
        migrations.RemoveField(
            model_name='main',
            name='smtpemail',
        ),
        migrations.RemoveField(
            model_name='main',
            name='smtpserver',
        ),
    ]
