# Generated by Django 3.0.1 on 2020-05-10 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200511_0107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Main',
        ),
    ]
