# Generated by Django 3.0.1 on 2020-05-10 22:10

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('status', models.CharField(choices=[('True', 'Evet'), ('False', 'Hayir')], default='', max_length=40)),
                ('title', models.CharField(max_length=15)),
                ('about', ckeditor_uploader.fields.RichTextUploadingField()),
                ('keyword', models.TextField(max_length=10000)),
                ('description', models.TextField(max_length=10000)),
                ('company', models.TextField(max_length=10000)),
                ('smtpserver', models.CharField(max_length=44)),
                ('smtpemail', models.CharField(max_length=44)),
                ('smtpPassword', models.CharField(max_length=15)),
                ('smtpPort', models.CharField(max_length=15)),
                ('pagefa', models.CharField(max_length=15)),
                ('pagetw', models.CharField(max_length=15)),
                ('pageyt', models.CharField(max_length=15)),
                ('pageLink', models.CharField(max_length=15)),
                ('pageTe', models.CharField(default=0, max_length=20)),
                ('icon', models.ImageField(blank=True, upload_to='images/')),
                ('name_set', models.CharField(default='-', max_length=20)),
            ],
        ),
    ]
