# Generated by Django 3.0.1 on 2020-06-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.IntegerField()),
                ('question', models.CharField(default='', max_length=150)),
                ('answer', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('True', 'Evet'), ('False', 'Hayir')], default='', max_length=40)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
